import type { Episode, Guest, ReleaseGates } from '../types';

export const seedGuests: Guest[] = [
  {
    id: 'guest-rebecca',
    name: 'Rebecca',
    slug: 'rebecca',
    bio: 'A woman of deep faith sharing her journey of identity and purpose.',
    topics: ['identity', 'faith', 'motherhood'],
    status: 'confirmed',
    episodeIds: ['ep-s01e01', 'ep-s01e03'],
    isPublic: true,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'guest-jaeden',
    name: 'Jaeden',
    slug: 'jaeden',
    bio: 'A musician and entrepreneur helping artists build sustainable businesses.',
    topics: ['business', 'music', 'art'],
    status: 'proposed',
    episodeIds: ['ep-s01e02'],
    isPublic: false,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'guest-rosina',
    name: 'Rosina',
    slug: 'rosina',
    bio: 'A mother and woman of faith navigating the beautiful tension of family and calling.',
    topics: ['faith', 'motherhood', 'identity'],
    status: 'proposed',
    episodeIds: ['ep-s01e03'],
    isPublic: false,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'guest-noah',
    name: 'Noah',
    slug: 'noah',
    bio: 'A worship leader sharing the highs and lows of leading others in praise.',
    topics: ['worship', 'faith', 'community'],
    status: 'proposed',
    episodeIds: ['ep-s01e04'],
    isPublic: false,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
];

const createDefaultReleaseGates = (): ReleaseGates => ({
  story: { status: 'pending' },
  technical: { status: 'pending' },
  brand: { status: 'pending' },
  rights: { status: 'pending' },
  metadata: { status: 'pending' },
});

export const seedEpisodes: Episode[] = [
  {
    id: 'ep-s01e01',
    seriesNumber: 'S01E01',
    title: 'IDENTITY',
    slug: 'identity',
    description:
      'In our debut episode, Rebecca joins Marchette for a raw and powerful conversation about what it truly means to know who you are — beyond titles, roles, and expectations. This is an episode about returning to yourself.',
    stage: 'production_capture',
    status: 'confirmed',
    guestIds: ['guest-rebecca'],
    recordingDate: new Date('2026-07-24'),
    releaseDate: new Date('2026-08-01'),
    releaseGates: {
      story: { status: 'passed', notes: 'Narrative arc approved by Marchette.' },
      technical: { status: 'in_review', notes: 'Audio cleanup in progress.' },
      brand: { status: 'passed', notes: 'Brand voice and visual references approved.' },
      rights: { status: 'pending', notes: 'Guest release awaiting signature.' },
      metadata: { status: 'pending', notes: 'Title, show notes, and keywords in development.' },
    },
    tags: ['identity', 'faith', 'debut', 'season-1'],
    tasks: [],
    approvals: [],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-07-01'),
  },
  {
    id: 'ep-s01e02',
    seriesNumber: 'S01E02',
    title: 'Building Your Business as a Musician or Artist',
    slug: 'building-your-business-as-a-musician-or-artist',
    description:
      "Jaeden shares hard-won lessons about monetizing your gift without losing your soul. Whether you're a musician, artist, or creative entrepreneur, this conversation is for you.",
    stage: 'guest_development',
    status: 'proposed',
    guestIds: ['guest-jaeden'],
    releaseGates: createDefaultReleaseGates(),
    tags: ['business', 'music', 'art', 'entrepreneurship', 'season-1'],
    tasks: [],
    approvals: [],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'ep-s01e03',
    seriesNumber: 'S01E03',
    title: 'Faith and Motherhood',
    slug: 'faith-and-motherhood',
    description:
      'Rebecca and Rosina join forces for an intimate conversation about holding faith and motherhood together — the grace, the grit, and the glory in between.',
    stage: 'concept',
    status: 'proposed',
    guestIds: ['guest-rebecca', 'guest-rosina'],
    releaseGates: createDefaultReleaseGates(),
    tags: ['faith', 'motherhood', 'identity', 'season-1'],
    tasks: [],
    approvals: [],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'ep-s01e04',
    seriesNumber: 'S01E04',
    title: 'Highs and Lows of a Worship Leader',
    slug: 'highs-and-lows-of-a-worship-leader',
    description:
      'Noah opens up about the rarely-spoken reality of leading worship — the spiritual highs, the personal valleys, and what keeps him anchored when the music stops.',
    stage: 'concept',
    status: 'proposed',
    guestIds: ['guest-noah'],
    releaseGates: createDefaultReleaseGates(),
    tags: ['worship', 'faith', 'community', 'leadership', 'season-1'],
    tasks: [],
    approvals: [],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
];
