import { AlertTriangle, ArrowUpRight, CheckCircle2, CircleDashed, Clock3, Radio, ShieldCheck, Sparkles, type LucideIcon } from 'lucide-react';
import { AppShell, MuseBadge } from '../components/Shell';
import { connections, episodes } from '../data';

const gateData = [['Story','Passed'],['Technical','In Review'],['Brand','Passed'],['Rights','Blocked'],['Metadata','Pending']] as const;
const metrics: Array<{ label: string; value: string; note: string; icon: LucideIcon }> = [
  { label: 'Operating maturity', value: '63 / 100', note: 'Target: 85+ in 90 days', icon: ArrowUpRight },
  { label: 'Episodes in motion', value: '4', note: '1 scheduled · 3 proposed', icon: Radio },
  { label: 'Waiting approval', value: '7', note: '2 executive · 5 production', icon: Clock3 },
  { label: 'Rights risks', value: '2', note: 'Release blocked until cleared', icon: ShieldCheck },
];

export default function Dashboard() {
  return <AppShell>
    <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><MuseBadge/><h1 className="mt-3 font-serif text-4xl">Executive Control Center</h1><p className="mt-2 text-[#1B1734]/60">The next right action across production, release, audience, and growth.</p></div><button className="rounded-full bg-[#1B1734] px-5 py-3 text-sm font-semibold text-white">Ask Muse Intelligence</button></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, note, icon: Icon }) => <article key={label} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-[#1B1734]/5"><div className="flex items-center justify-between"><p className="text-sm text-[#1B1734]/55">{label}</p><Icon className="text-[#8B2C6F]" size={20}/></div><p className="mt-5 font-serif text-4xl">{value}</p><p className="mt-2 text-xs text-[#1B1734]/50">{note}</p></article>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]">
      <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-[#1B1734]/5"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl">Episode command board</h2><p className="text-sm text-[#1B1734]/50">Truth-preserving status by episode</p></div><span className="rounded-full bg-[#C9A227]/15 px-3 py-1 text-xs font-semibold">34 assets / episode</span></div><div className="mt-5 space-y-3">{episodes.map(ep => <div key={ep.id} className="rounded-2xl border border-[#1B1734]/8 p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><p className="text-xs font-semibold text-[#8B2C6F]">{ep.code} · {ep.status}</p><h3 className="mt-1 font-semibold">{ep.title}</h3><p className="text-sm text-[#1B1734]/50">{ep.guests.join(' + ')} · {ep.stage}</p></div><div className="min-w-44"><div className="flex justify-between text-xs"><span>Assets</span><span>{ep.completedAssets}/{ep.targetAssets}</span></div><div className="mt-2 h-2 rounded-full bg-[#1B1734]/8"><div className="h-2 rounded-full bg-[#8B2C6F]" style={{width:`${ep.completedAssets/ep.targetAssets*100}%`}}/></div></div></div></div>)}</div></article>
      <div className="space-y-5"><article className="rounded-3xl bg-[#1B1734] p-6 text-white"><div className="flex items-center gap-2"><Sparkles className="text-[#C9A227]"/><h2 className="font-serif text-2xl">Today’s signal</h2></div><p className="mt-4 leading-7 text-white/70">S01E01 is closest to release. Rights clearance and metadata completion are the critical path. Keep all proposed dates labeled until executive confirmation.</p><button className="mt-5 text-sm font-semibold text-[#D8A7B1]">Convert recommendation to tasks →</button></article><article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-[#1B1734]/5"><h2 className="font-serif text-2xl">Release gates</h2><div className="mt-4 space-y-3">{gateData.map(([gate,status]) => <div key={gate} className="flex items-center justify-between"><span>{gate}</span><span className="flex items-center gap-2 text-xs">{status === 'Passed' ? <CheckCircle2 size={16} className="text-green-700"/> : status === 'Blocked' ? <AlertTriangle size={16} className="text-red-700"/> : <CircleDashed size={16} className="text-[#8B2C6F]"/>}{status}</span></div>)}</div></article></div>
    </section>
    <section className="mt-5 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-[#1B1734]/5"><h2 className="font-serif text-2xl">Platform connection health</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{connections.map(c => <div key={c.name} className="rounded-2xl border border-[#1B1734]/8 p-4"><div className="flex items-center justify-between"><strong>{c.name}</strong><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[11px] font-semibold text-amber-900">{c.status}</span></div><p className="mt-2 text-xs leading-5 text-[#1B1734]/50">{c.capabilities.join(' · ')}</p></div>)}</div></section>
  </AppShell>;
}
